on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: docker
    services:
      dind:
        image: docker:dind

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: apk add --update bash nodejs npm jq

      - name: Deploy
        run: bash deploy.sh